# Provide a list of paths to MSA files for which you wish to generate training data
# currently all MSAs will be run under the same model, so make sure to only provide either
# DNA or AA data and not both
# note that at the moment this pipeline does not support partitioned analyses
msa_paths: [
   /paths/to/msa,
]


# either DNA or AA
data_type: "DNA"

# After running the pipeline, the outdir will contain a subdirectory for each given MSA
# each subdirectory contains:
# - a directory called "output_files": contains all RAxML-NG and IQ-Tree log files
# - an .sqlite3 database file containing all information, see README.md for database schema
outdir: "data/"

# provide the paths to the RAxML-NG, IQ-Tree, and Parsimonator executables here
software:
  raxml-ng:
    command: "path/to/raxml-ng" # https://github.com/tschuelia/raxml-ng
    model: GTR+G
    threads: 2
  iqtree:
    command: "path/to/iqtree" # http://www.iqtree.org
    model: GTR+FO+G4
    threads: 2
  parsimonator:
    command: "path/to/parsimonator" # https://github.com/stamatak/Parsimonator-1.0.2

# these variables are used for coding and debugging, we do not recommend changing them
_debug:
  _num_pars_trees: 50
  _num_rand_trees: 50
  _num_parsimony_trees: 100