# Provide a list of paths to MSA files for which you wish to generate training data
# currently all MSAs will be run under the same model, so make sure to only provide either
# DNA or AA data and not both

msa_paths: [
   /path/to/msa1,
   /path/to/msa2,
   ...
]

# to use partitioned MSAs, provide a link to the partition file for each MSA
# the partition file should be in a RAxML-NG and IQ-Tree compatible format
# note that the MSA features will be computed for the entire alignment
# In this case, the msa_paths list should be a list of lists:
# msa_paths: [
#    [/path/to/msa1, /path/to/msa1.part],
#    /path/to/msa2, /path/to/msa2.part],
#    ...
# ]

# After running the pipeline, the outdir will contain a subdirectory for each given MSA
# each subdirectory contains:
# - a directory called "output_files": contains all RAxML-NG and IQ-Tree log files
# - an .sqlite3 database file containing all information, see README.md for database schema
outdir: results/

software:
  raxml-ng:
    command: /Users/julia/Desktop/Promotion/software/raxml-ng/bin/raxml-ng
    model: GTR+G
  iqtree:
    command: /Users/julia/Desktop/Promotion/software/iqtree-2.1.3-MacOSX/bin/iqtree2
    model: GTR+G4+FO
    threads: 2

_debug:
  _num_pars_trees: 50
  _num_rand_trees: 50
  _num_parsimony_trees: 100
