name: difficulty
channels:
  - bioconda
  - conda-forge
  - defaults
  - conda-canary
dependencies:
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - pip
    - peewee
    -  biopython
