name: difficulty
channels:
  - bioconda
  - conda-forge
  - defaults
  - conda-canary
dependencies:
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - peewee
  - biopython
  - treelite
  - git-lfs
  - rpy2
  - r-raster
  - r-rmpfr
  - pip:
    - git+https://github.com/tschuelia/PyPythia.git
