name: difficulty
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - peewee
  - biopython
  - treelite
  - git-lfs
  - rpy2
  - r-devtools
  - r-essentials
  - regex
  - pyarrow
  - ete3
  - pip
  - pip:
    - git+https://github.com/tschuelia/PyPythia.git
