name: difficulty
channels:
  - bioconda
  - conda-forge
  - defaults
  - conda-canary
dependencies:
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - peewee
  - biopython
  - treelite
  - pip
    - git+https://github.com/tschuelia/PyPhyPred.git
