name: difficulty
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake
  - ca-certificates
  - certifi
  - openssl
  - pandas
  - peewee
  - biopython
  - treelite
  - pyarrow
  - pip
  - pip:
    - git+https://github.com/tschuelia/PyPythia.git
